package edd_hospital_.vista;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import edd_hospital_.modelo.Datos;
import edd_hospital_.modelo.Dependencia;
import edd_hospital_.modelo.CreadorDeNodos;
import edd_hospital_.modelo.Hospitales;
import edd_hospital_.multi_lista.NodoML;
import static edd_hospital_.vista.Validaciones.eliminaCopyPasteCut;
import interfaces.VentanaEditable;
import interfaces.VentanaRegistrable;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class vtnDependencia extends javax.swing.JDialog implements VentanaRegistrable, VentanaEditable
{

    private NodoML nodoDependencia;
    Dependencia objetoEditable;

    /**
     * Creates new form vtnDependencia
     *
     * @param parent
     * @param modal
     */
    public vtnDependencia(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        jtfClave.setText(String.format("D%03d", Datos.getNumeroDeRegistros() + 1));
        //    this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Fondo = new javax.swing.JPanel();
        Dependencia = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfClave = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        registrarDepBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        Cancelar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 285));
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(153, 153, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dependencia.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel5.setText("Cve Dependencia:");

        jtfClave.setEditable(false);
        jtfClave.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jtfClave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfClave.setFocusable(false);
        jtfClave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtfClaveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtfClaveKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel7.setText("Tipo: ");

        jcbTipo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Opciones-", "Federal", "Estatal", "Municipal" }));
        jcbTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        registrarDepBtn.setBackground(new java.awt.Color(153, 153, 255));
        registrarDepBtn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        registrarDepBtn.setText("Guardar");
        registrarDepBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarDepBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registrarDepBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel8.setText("Nombre:");

        jtfNombre.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jtfNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfNombreActionPerformed(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtfNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtfNombreKeyTyped(evt);
            }
        });

        Cancelar1.setBackground(new java.awt.Color(153, 153, 255));
        Cancelar1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        Cancelar1.setText("Limpiar");
        Cancelar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cancelar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DependenciaLayout = new javax.swing.GroupLayout(Dependencia);
        Dependencia.setLayout(DependenciaLayout);
        DependenciaLayout.setHorizontalGroup(
            DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DependenciaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrarDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5)))
                .addGap(51, 51, 51)
                .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DependenciaLayout.createSequentialGroup()
                        .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(169, Short.MAX_VALUE))
                    .addGroup(DependenciaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        DependenciaLayout.setVerticalGroup(
            DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DependenciaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DependenciaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DependenciaLayout.createSequentialGroup()
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(49, 49, 49)
                .addGroup(DependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarDepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar1))
                .addGap(87, 87, 87))
        );

        Fondo.add(Dependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 710, 340));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel6.setText("-DEPENDENCIAS-");
        Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        getContentPane().add(Fondo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void configurarParaEditable()
    {
        jtfNombre.setEditable(false);
        jtfNombre.setFocusable(false);
    }
     private void jtfClaveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfClaveKeyTyped
     {//GEN-HEADEREND:event_jtfClaveKeyTyped
         Validaciones.validaAlfabeticos(evt, 15, jtfNombre.getText());
     }//GEN-LAST:event_jtfClaveKeyTyped

     private void registrarDepBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registrarDepBtnActionPerformed
     {//GEN-HEADEREND:event_registrarDepBtnActionPerformed

         String nombre = jtfNombre.getText();
         String tipo = (String) jcbTipo.getSelectedItem();
         if (nombre.isEmpty() || tipo.equals("-Opciones-"))
         {
             javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos",
                     "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
             return;
         }
         CreadorDeNodos n = new CreadorDeNodos();
         this.nodoDependencia = n.NodoDependencia(tipo, nombre);
         objetoEditable = new Dependencia(tipo, nombre, jtfClave.getText());
         this.dispose();
     }//GEN-LAST:event_registrarDepBtnActionPerformed

    public JButton getRegistrarDepBtn()
    {
        return registrarDepBtn;
    }

    @Override
    public NodoML getNodoRegistrado()
    {
        return this.nodoDependencia;
    }
    @Override
    public void cargarDatos(NodoML n)
    {

        if (n == null)
        {
            throw new IllegalArgumentException("No se pudieron cargar los datos porque el nodo es null");
        }
        if (n.getObj() instanceof Dependencia d)
        {
            jtfNombre.setText(d.getNombre());
            jtfClave.setText(d.getClaveD());
            jcbTipo.setSelectedItem(d.getTipo());
        } else
        {
            throw new IllegalArgumentException("EL objeto es null o no es de tipo dependencia");
        }

    }
     private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfNombreKeyTyped
     {//GEN-HEADEREND:event_jtfNombreKeyTyped
         // TODO add your handling code here:
         eliminaCopyPasteCut(evt);
         Validaciones.validaAlfabeticos(evt, 35, jtfNombre.getText());
     }//GEN-LAST:event_jtfNombreKeyTyped

    public JTextField getJtfNombre()
    {
        return jtfNombre;
    }

    public void setJtfNombre(JTextField jtfNombre)
    {
        this.jtfNombre = jtfNombre;
    }


    private void jtfClaveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfClaveKeyPressed
    {//GEN-HEADEREND:event_jtfClaveKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClaveKeyPressed

    private void jtfNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfNombreKeyPressed
    {//GEN-HEADEREND:event_jtfNombreKeyPressed
        // TODO add your handling code here:
        eliminaCopyPasteCut(evt);
        //  Validaciones.validaAlfabeticos(evt);

    }//GEN-LAST:event_jtfNombreKeyPressed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfNombreActionPerformed
    {//GEN-HEADEREND:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Cancelar1ActionPerformed
    {//GEN-HEADEREND:event_Cancelar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar1ActionPerformed
    public static void main(String[] args)
    {
        vtnDependencia vtn = new vtnDependencia(null, true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar1;
    private javax.swing.JPanel Dependencia;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JTextField jtfClave;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JButton registrarDepBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjetoEditado()
    {
        return objetoEditable;
    }

}
