package edd_hospital_.vista;

import edd_hospital_.modelo.BicolaPacientes;
import edd_hospital_.modelo.Niveles;
import edd_hospital_.modelo.RemodelacionHospitales;
import interfaces.MostrableEnTabla;
import edd_hospital_.multi_lista.NodoML;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

public class VtnGeneral2 extends javax.swing.JFrame
{

    DefaultTableModel modeloTabla = new DefaultTableModel()
    {
        @Override
        public boolean isCellEditable(int row, int column)
        {
            return false; // ninguna celda editable

        }
    };

    public VtnGeneral2()
    {

        initComponents();
        jtbTabla.getTableHeader().setReorderingAllowed(false);
        jtbTabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void actualizarPanelNavegacion(List<String> ruta)
    {
        panelNavegacion.removeAll();
        for (int i = 0; i < ruta.size(); i++)
        {
            String s = ruta.get(i);
            JLabel ubicacion = new JLabel(s);
            ubicacion.setFont(new Font("Arial", Font.PLAIN, 14));
            panelNavegacion.add(ubicacion);
            // Si no es el último elemento, agregar flecha
            try
            {
                if (i < ruta.size() - 1)
                {
                    JLabel flecha = new JLabel(new ImageIcon(getClass().getResource("/edd_hospital_/vista/imagenes/flecha.png")));
                    panelNavegacion.add(flecha);
                }
            } catch (Exception e)
            {
                JLabel flecha = new JLabel(">");
                panelNavegacion.add(flecha);
                System.out.println(e.getMessage());
            }
        }
        panelNavegacion.revalidate(); // Actualiza la interfaz
        panelNavegacion.repaint();    // Repinta el panel para mostrar los cambios
    }

    public void mostrarEnLaTabla(MostrableEnTabla modelProvider, NodoML raiz)
    {
        if (modelProvider == null)
        {
            return;
        }
        resetearModeloTabla();
        for (String cabecera : modelProvider.getNombreCabeceras())
        {
            modeloTabla.addColumn(cabecera);
        }
        if (raiz != null)
        {
            for (Object fila[] : modelProvider.getDatos(raiz))
            {
                modeloTabla.addRow(fila);
            }
        }
        jtbTabla.setModel(modeloTabla);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    public void resetearModeloTabla()
    {
        modeloTabla.setColumnCount(0);
        modeloTabla.setRowCount(0);
    }

    public JButton getBtnVolver()
    {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver)
    {
        this.btnVolver = btnVolver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jpnBotones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEspera = new javax.swing.JButton();
        btnAltaPaciente = new javax.swing.JButton();
        btnRemodelacion = new javax.swing.JButton();
        btnRemodelacionTerminada = new javax.swing.JButton();
        jpnSuperior = new javax.swing.JPanel();
        panelNavegacion = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 530));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jpnBotones.setBackground(new java.awt.Color(204, 204, 204));

        btnNuevo.setBackground(new java.awt.Color(153, 153, 255));
        btnNuevo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(153, 153, 255));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(153, 153, 255));
        btnModificar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEspera.setBackground(new java.awt.Color(153, 153, 255));
        btnEspera.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnEspera.setText("Mostrar pacientes en espera");
        btnEspera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEspera.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEsperaActionPerformed(evt);
            }
        });

        btnAltaPaciente.setBackground(new java.awt.Color(153, 153, 255));
        btnAltaPaciente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnAltaPaciente.setText("Dar de alta paciente");
        btnAltaPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAltaPaciente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAltaPacienteActionPerformed(evt);
            }
        });

        btnRemodelacion.setBackground(new java.awt.Color(153, 153, 255));
        btnRemodelacion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnRemodelacion.setText("Remodelacion de Hospital");
        btnRemodelacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRemodelacion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemodelacionActionPerformed(evt);
            }
        });

        btnRemodelacionTerminada.setBackground(new java.awt.Color(153, 153, 255));
        btnRemodelacionTerminada.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnRemodelacionTerminada.setText("Remodelacion Terminada");
        btnRemodelacionTerminada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jpnBotonesLayout = new javax.swing.GroupLayout(jpnBotones);
        jpnBotones.setLayout(jpnBotonesLayout);
        jpnBotonesLayout.setHorizontalGroup(
            jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemodelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAltaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemodelacionTerminada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnBotonesLayout.setVerticalGroup(
            jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemodelacion)
                    .addComponent(btnAltaPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemodelacionTerminada)
                    .addComponent(btnEspera))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBotonesLayout.createSequentialGroup()
                .addGroup(jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar)
                    .addComponent(btnNuevo))
                .addGap(23, 23, 23))
        );

        jPanel4.add(jpnBotones, java.awt.BorderLayout.PAGE_END);

        jpnSuperior.setBackground(new java.awt.Color(153, 153, 255));
        jpnSuperior.setForeground(new java.awt.Color(153, 153, 255));

        panelNavegacion.setBackground(new java.awt.Color(255, 255, 255));
        panelNavegacion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 15));

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setText("TIPO_NIVEL");
        lblTitulo.setToolTipText("");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd_hospital_/vista/imagenes/atras.png"))); // NOI18N
        btnVolver.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVolver.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnSuperiorLayout = new javax.swing.GroupLayout(jpnSuperior);
        jpnSuperior.setLayout(jpnSuperiorLayout);
        jpnSuperiorLayout.setHorizontalGroup(
            jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSuperiorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelNavegacion, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpnSuperiorLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnSuperiorLayout.setVerticalGroup(
            jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(25, 25, 25)
                .addGroup(jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNavegacion, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.add(jpnSuperior, java.awt.BorderLayout.PAGE_START);

        jtbTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jtbTabla.setRequestFocusEnabled(false);
        jtbTabla.setRowHeight(25);
        jtbTabla.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jtbTabla.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jtbTablaMouseClicked(evt);
            }
        });
        jtbTabla.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtbTablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbTabla);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtbTablaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtbTablaKeyPressed
    {//GEN-HEADEREND:event_jtbTablaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtbTablaKeyPressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNuevoActionPerformed
    {//GEN-HEADEREND:event_btnNuevoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnNuevoActionPerformed

    public JButton getBtnNuevo()
    {
        return btnNuevo;
    }

    public void setBtnNuevo(JButton btnNuevo)
    {
        this.btnNuevo = btnNuevo;
    }

    private void btnEsperaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEsperaActionPerformed
    {//GEN-HEADEREND:event_btnEsperaActionPerformed

    }//GEN-LAST:event_btnEsperaActionPerformed

    public JButton getBtnEspera()
    {
        return btnEspera;
    }

    public void setBtnEspera(JButton btnEspera)
    {
        this.btnEspera = btnEspera;
    }

    private void jtbTablaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jtbTablaMouseClicked
    {//GEN-HEADEREND:event_jtbTablaMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jtbTablaMouseClicked

    public JLabel getLblTitulo()
    {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo)
    {
        this.lblTitulo = lblTitulo;
    }

    public JTable getJtbTabla()
    {
        return jtbTabla;
    }

    public void setJtbTabla(JTable jtbTabla)
    {
        this.jtbTabla = jtbTabla;
    }

    public boolean esDobleClickIzquierdo(MouseEvent evt)
    {
        return evt.getClickCount() == 2 && SwingUtilities.isLeftMouseButton(evt);
    }

    public String getNombreSeleccionado(Niveles nivel, String dependenciaPadre)
    {
        String seleccionado = getNombreSeleccionado2();
        if (seleccionado == null)
        {
            throw new IllegalStateException("Debes seleccionar algo");
        }
        if (nivel == Niveles.HOSPITAL)
        {
            String nombreDeSuTemporal = RemodelacionHospitales.buscaSuTemporal(dependenciaPadre, seleccionado);
            if (nombreDeSuTemporal != null)
            {
                return nombreDeSuTemporal;
            }
        }
        return seleccionado;
    }

    public String getNombreSeleccionado2()
    {
        String claveSeleccionado = null;
        int filaSeleccionada = jtbTabla.getSelectedRow();
        int columna = 1;
        if (filaSeleccionada == -1)
        {
            throw new IllegalStateException("Debes seleccionar algo");
        }
        if (filaSeleccionada != -1)
        {
            Object valor = jtbTabla.getValueAt(filaSeleccionada, columna);
            claveSeleccionado = (String) valor;
        }
        return claveSeleccionado;
    }


    public JButton getBtnModificar()
    {
        return btnModificar;
    }

    public void setBtnModificar(JButton btnModificar)
    {
        this.btnModificar = btnModificar;
    }

    public JButton getBtnEliminar()
    {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar)
    {
        this.btnEliminar = btnEliminar;
    }

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarActionPerformed
    {//GEN-HEADEREND:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAltaPacienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAltaPacienteActionPerformed
    {//GEN-HEADEREND:event_btnAltaPacienteActionPerformed

    }//GEN-LAST:event_btnAltaPacienteActionPerformed

    private void btnRemodelacionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemodelacionActionPerformed
    {//GEN-HEADEREND:event_btnRemodelacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemodelacionActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVolverActionPerformed
    {//GEN-HEADEREND:event_btnVolverActionPerformed

    }//GEN-LAST:event_btnVolverActionPerformed

    public JButton getBtnAltaPaciente()
    {
        return btnAltaPaciente;
    }

    public void setBtnAltaPaciente(JButton btnAltaPaciente)
    {
        this.btnAltaPaciente = btnAltaPaciente;
    }

    public void mostrarBotonAltaPaciente(Niveles nivelActual)
    {
        if (nivelActual == Niveles.PACIENTE)
        {
            btnAltaPaciente.setVisible(true);
        } else
        {
            btnAltaPaciente.setVisible(false);
        }
    }

    public JButton getBtnRemodelacion()
    {
        return btnRemodelacion;
    }

    public void setBtnRemodelacion(JButton btnRemodelacion)
    {
        this.btnRemodelacion = btnRemodelacion;
    }

    public JButton getBtnRemodelacionTerminada()
    {
        return btnRemodelacionTerminada;
    }

    public void setBtnRemodelacionTerminada(JButton btnRemodelacionTerminada)
    {
        this.btnRemodelacionTerminada = btnRemodelacionTerminada;
    }

    public void mostrarBotonesRemodelacion(Niveles nivelActual)
    {
        if (nivelActual == Niveles.HOSPITAL)
        {
            btnRemodelacion.setVisible(true);
            btnRemodelacionTerminada.setVisible(true);
        } else
        {
            btnRemodelacion.setVisible(false);
            btnRemodelacionTerminada.setVisible(false);
        }
    }

    public void mostrarBotonPacienteEnEspera(Niveles nivelActual)
    {
        if (nivelActual == Niveles.HOSPITAL)
        {
            btnEspera.setVisible(true);
        } else
        {
            btnEspera.setVisible(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnGeneral2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new VtnGeneral2().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaPaciente;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEspera;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRemodelacion;
    private javax.swing.JButton btnRemodelacionTerminada;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnBotones;
    private javax.swing.JPanel jpnSuperior;
    private javax.swing.JTable jtbTabla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelNavegacion;
    // End of variables declaration//GEN-END:variables
}
