package edd_hospital_.vista;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import edd_hospital_.modelo.Datos;
import edd_hospital_.modelo.Hospitales;
import edd_hospital_.modelo.CreadorDeNodos;
import edd_hospital_.multi_lista.NodoML;
import static edd_hospital_.vista.Validaciones.eliminaCopyPasteCut;
import interfaces.VentanaEditable;
import interfaces.VentanaRegistrable;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class vtnHospitales extends javax.swing.JDialog implements VentanaRegistrable, VentanaEditable
{

    private NodoML nodoHospital;
    Hospitales objetoEditable;

    /**
     * Creates new form vtnHospitales
     *
     * @param parent
     * @param modal
     */
    public vtnHospitales(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        jtfClave.setText(String.format("H%03d", Datos.getNumeroDeRegistros() + 1));

    }

    public void configurarParaEditable()
    {
        jtfNombre.setEditable(false);
        jtfNombre.setFocusable(false);

    }

    @Override
    public void cargarDatos(NodoML n)
    {

        if (n == null)
        {
            throw new IllegalArgumentException("No se pudieron cargar los datos porque el nodo es null");
        }
        if (n.getObj() instanceof Hospitales h)
        {
            jtaDireccion.setText(h.getDireccion());
            jtfNombre.setText(h.getNombre());
            jtfClave.setText(h.getClaveH());
            jcbNivel.setSelectedIndex(h.getNivel());
        } else
        {
            throw new IllegalArgumentException("EL objeto es null o no es de tipo Hospitales");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Fondo = new javax.swing.JPanel();
        Hospital = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfClave = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jcbNivel = new javax.swing.JComboBox<>();
        jtfNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtaDireccion = new javax.swing.JTextField();
        Cancelar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(153, 153, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hospital.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel6.setText("Cve:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel8.setText("Dirección:");

        jtfClave.setEditable(false);
        jtfClave.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jtfClave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfClave.setFocusable(false);
        jtfClave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtfClaveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtfClaveKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel14.setText("Nivel:");

        btnGuardar.setBackground(new java.awt.Color(153, 153, 255));
        btnGuardar.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarActionPerformed(evt);
            }
        });

        jcbNivel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jcbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Opciones-", "1", "2", "3" }));
        jcbNivel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbNivel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbNivelActionPerformed(evt);
            }
        });

        jtfNombre.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jtfNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfNombreActionPerformed(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtfNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtfNombreKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel9.setText("Nombre:");

        jtaDireccion.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jtaDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtaDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtaDireccion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtaDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtaDireccionKeyTyped(evt);
            }
        });

        Cancelar1.setBackground(new java.awt.Color(153, 153, 255));
        Cancelar1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        Cancelar1.setText("Limpiar");
        Cancelar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cancelar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HospitalLayout = new javax.swing.GroupLayout(Hospital);
        Hospital.setLayout(HospitalLayout);
        HospitalLayout.setHorizontalGroup(
            HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospitalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(76, 76, 76)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HospitalLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        HospitalLayout.setVerticalGroup(
            HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospitalLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtaDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        Fondo.add(Hospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 710, 340));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel7.setText("-HOSPITALES-");
        Fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private void jtfClaveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfClaveKeyTyped
     {//GEN-HEADEREND:event_jtfClaveKeyTyped
         eliminaCopyPasteCut(evt);
         Validaciones.validaAlfanumerico(evt, 20, jtfNombre.getText());
     }//GEN-LAST:event_jtfClaveKeyTyped

     private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarActionPerformed
     {//GEN-HEADEREND:event_btnGuardarActionPerformed
         try
         {

             int nivel = jcbNivel.getSelectedIndex();
             String direccion = jtaDireccion.getText();
             String nombre = jtfNombre.getText().trim();

             if (nombre.isEmpty() || nivel == 0 || direccion.isEmpty())
             {
                 JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos",
                         "Error", JOptionPane.ERROR_MESSAGE);
                 return;
             }
             CreadorDeNodos n = new CreadorDeNodos();
             this.nodoHospital = n.NodoHospitales(direccion, nivel, nombre);
             objetoEditable = new Hospitales(direccion, nivel, nombre, jtfClave.getText());
             dispose();
         } catch (RuntimeException ex)
         {
             JOptionPane.showMessageDialog(this, "Error al registrar el hospital: " + ex.getMessage(),
                     "Error", JOptionPane.ERROR_MESSAGE);
         }
     }//GEN-LAST:event_btnGuardarActionPerformed

    @Override
    public NodoML getNodoRegistrado()
    {
        return this.nodoHospital;
    }

    private void jcbNivelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbNivelActionPerformed
    {//GEN-HEADEREND:event_jcbNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNivelActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfNombreActionPerformed
    {//GEN-HEADEREND:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfNombreKeyTyped
    {//GEN-HEADEREND:event_jtfNombreKeyTyped
        Validaciones.validaAlfanumerico(evt, 20, jtfNombre.getText());
        eliminaCopyPasteCut(evt);
    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtaDireccionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtaDireccionKeyTyped
    {//GEN-HEADEREND:event_jtaDireccionKeyTyped
        Validaciones.validaAlfanumerico(evt, 30, jtaDireccion.getText());
        eliminaCopyPasteCut(evt);
    }//GEN-LAST:event_jtaDireccionKeyTyped

    private void jtaDireccionKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtaDireccionKeyPressed
    {//GEN-HEADEREND:event_jtaDireccionKeyPressed
        Validaciones.validaAlfanumerico(evt, 30, jtaDireccion.getText());
        eliminaCopyPasteCut(evt);
    }//GEN-LAST:event_jtaDireccionKeyPressed

    private void jtfNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfNombreKeyPressed
    {//GEN-HEADEREND:event_jtfNombreKeyPressed
        Validaciones.validaAlfanumerico(evt, 20, jtfNombre.getText());
        eliminaCopyPasteCut(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreKeyPressed

    private void jtfClaveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtfClaveKeyPressed
    {//GEN-HEADEREND:event_jtfClaveKeyPressed
        eliminaCopyPasteCut(evt);
        Validaciones.validaAlfanumerico(evt, 20, jtfNombre.getText());
    }//GEN-LAST:event_jtfClaveKeyPressed

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Cancelar1ActionPerformed
    {//GEN-HEADEREND:event_Cancelar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnHospitales.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnHospitales.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnHospitales.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnHospitales.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                vtnHospitales vtn = new vtnHospitales(null, true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar1;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Hospital;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcbNivel;
    private javax.swing.JTextField jtaDireccion;
    private javax.swing.JTextField jtfClave;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getObjetoEditado()
    {
        return objetoEditable;
    }

}
