package edd_hospital_.vista;

import edd_hospital_.modelo.Bicola;
import edd_hospital_.modelo.BicolaPacientes;
import edd_hospital_.modelo.LogicaNegocioJose;
import edd_hospital_.modelo.Paciente;
import edd_hospital_.multi_lista.NodoML;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class VtnPacientesEnEspera extends javax.swing.JFrame
{

    private final BicolaPacientes pacientesEliminado = new BicolaPacientes();

    DefaultTableModel modeloTabla = new DefaultTableModel()
    {
        @Override
        public boolean isCellEditable(int row, int column)
        {
            return false;
        }
    };

    public VtnPacientesEnEspera()
    {
        initComponents();
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void ponerPacientesOncoEnLaTabla()
    {
        modeloTabla = (DefaultTableModel) jTable1.getModel();
        if (LogicaNegocioJose.pacientesEnEspera != null)
        {
            NodoML nodoPaciente = LogicaNegocioJose.pacientesEnEspera.eliminaNodoPacienteOncologia();
            modeloTabla.setRowCount(0);
            if (nodoPaciente == null)
            {
                JOptionPane.showMessageDialog(null, "no hay pacientes en oncologia");
            }
            while (nodoPaciente != null)
            {
                Paciente paciente = (Paciente) nodoPaciente.getObj();

                modeloTabla.addRow(new Object[]
                {
                    paciente.getClaveP(),
                    paciente.getNombre(),
                    paciente.getSexo(),
                    paciente.getEstatus(),
                    paciente.getVigencia()
                });
                pacientesEliminado.insertaPacienteOncologia(nodoPaciente);
                nodoPaciente = LogicaNegocioJose.pacientesEnEspera.eliminaNodoPacienteOncologia();

            }
            jTable1.setModel(modeloTabla);
            nodoPaciente = pacientesEliminado.eliminaNodoPacienteOncologia();
            while (nodoPaciente != null)
            {

                LogicaNegocioJose.pacientesEnEspera.insertaPacienteOncologia(nodoPaciente);
                nodoPaciente = pacientesEliminado.eliminaNodoPacienteOncologia();
            }
        }

    }

    public void ponerPacientesNeuroEnLaTabla()
    {
        modeloTabla = (DefaultTableModel) jTable1.getModel();
        if (LogicaNegocioJose.pacientesEnEspera != null)
        {
            NodoML nodoPaciente = LogicaNegocioJose.pacientesEnEspera.eliminaNodoPacienteNeuro();
            modeloTabla.setRowCount(0);
            if (nodoPaciente == null)
            {
                JOptionPane.showMessageDialog(null, "no hay pacientes en neurologia");
            }
            while (nodoPaciente != null)
            {
                Paciente paciente = (Paciente) nodoPaciente.getObj();

                modeloTabla.addRow(new Object[]
                {
                    paciente.getClaveP(),
                    paciente.getNombre(),
                    paciente.getSexo(),
                    paciente.getEstatus(),
                    paciente.getVigencia()
                });
                pacientesEliminado.insertaPacienteNeuro(nodoPaciente);
                nodoPaciente = LogicaNegocioJose.pacientesEnEspera.eliminaNodoPacienteNeuro();

            }
            jTable1.setModel(modeloTabla);
            nodoPaciente = pacientesEliminado.eliminaNodoPacienteNeuro();
            while (nodoPaciente != null)
            {

                LogicaNegocioJose.pacientesEnEspera.insertaPacienteNeuro(nodoPaciente);
                nodoPaciente = pacientesEliminado.eliminaNodoPacienteNeuro();
            }
        }

    }
    //        //nodo del paciente eliminado
    //        // sacas el objeto con los datos 
    //        //poner los datos en la tabla 
    //        //se inserta en la bicola pacienteEliminado
    //        //se elDiminan de la bicola auxiliar y regresan a la bicolaPaciente hasta que el eliminado sea nulo

    public JButton getBtnVolver()
    {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver)
    {
        this.btnVolver = btnVolver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jpnLateral = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jpnBotones = new javax.swing.JPanel();
        btnNeurologia = new javax.swing.JButton();
        btnOncologia = new javax.swing.JButton();
        jpnSuperior = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 530));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jpnLateral.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jpnLateralLayout = new javax.swing.GroupLayout(jpnLateral);
        jpnLateral.setLayout(jpnLateralLayout);
        jpnLateralLayout.setHorizontalGroup(
            jpnLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jpnLateralLayout.setVerticalGroup(
            jpnLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        jPanel1.add(jpnLateral, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(255, 102, 204));
        jPanel4.setLayout(new java.awt.BorderLayout());

        btnNeurologia.setText("Pacientes de neurologia");
        btnNeurologia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNeurologiaActionPerformed(evt);
            }
        });

        btnOncologia.setText("Pacientes de oncologia");
        btnOncologia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOncologiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnBotonesLayout = new javax.swing.GroupLayout(jpnBotones);
        jpnBotones.setLayout(jpnBotonesLayout);
        jpnBotonesLayout.setHorizontalGroup(
            jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBotonesLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnOncologia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(btnNeurologia)
                .addGap(145, 145, 145))
        );
        jpnBotonesLayout.setVerticalGroup(
            jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBotonesLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnOncologia, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnNeurologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        jPanel4.add(jpnBotones, java.awt.BorderLayout.PAGE_END);

        jpnSuperior.setBackground(new java.awt.Color(153, 153, 255));

        btnVolver.setText("volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVolverActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Pacientes en espera: ");
        lblTitulo.setToolTipText("");

        javax.swing.GroupLayout jpnSuperiorLayout = new javax.swing.GroupLayout(jpnSuperior);
        jpnSuperior.setLayout(jpnSuperiorLayout);
        jpnSuperiorLayout.setHorizontalGroup(
            jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSuperiorLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnVolver)
                .addGap(209, 209, 209)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        jpnSuperiorLayout.setVerticalGroup(
            jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSuperiorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(lblTitulo))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel4.add(jpnSuperior, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Clave", "Nombre", "Sexo", "Estatus", "Vigencia"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVolverActionPerformed
    {//GEN-HEADEREND:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnOncologiaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOncologiaActionPerformed
    {//GEN-HEADEREND:event_btnOncologiaActionPerformed
        ponerPacientesOncoEnLaTabla();
    }//GEN-LAST:event_btnOncologiaActionPerformed

    private void btnNeurologiaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNeurologiaActionPerformed
    {//GEN-HEADEREND:event_btnNeurologiaActionPerformed
        ponerPacientesNeuroEnLaTabla();
    }//GEN-LAST:event_btnNeurologiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPacientesEnEspera.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new VtnPacientesEnEspera().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNeurologia;
    private javax.swing.JButton btnOncologia;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpnBotones;
    private javax.swing.JPanel jpnLateral;
    private javax.swing.JPanel jpnSuperior;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
